// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbdfyxygltisvtpgkqok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiZGZ5eHlnbHRpc3Z0cGdrcW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODIzMjAsImV4cCI6MjA2OTY1ODMyMH0.v7-DWrgL51d9PlMmJdw2Zm2UJDVMbtcEksk3kQZnHz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});